name: quiz_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  get: ^4.6.3
  get_storage: ^2.0.3
  http: ^0.13.5
  logger: ^1.1.0
  path_provider: ^2.0.11
  screenshot: ^1.2.3
  share_plus: ^4.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  